backend:
  name: github
  repo: foxah047-stack/cgbvrr.axiomorphe.ca
  branch: main

media_folder: assets/img
public_folder: /assets/img

collections:
  - name: posts
    label: Nouvelles
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Layout, name: layout, widget: hidden, default: post }
      - { label: Titre, name: title, widget: string }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Catégorie, name: categorie, widget: string }
      - { label: Projet, name: projet, widget: string }
      - { label: Auteur, name: auteur, widget: string }
      - { label: Extrait, name: excerpt, widget: text }
      - { label: Contenu, name: body, widget: markdown }